import { User, Task } from "./types";

const baseUsers: Omit<User, "_id">[] = [
  {
    id: "u1",
    email: "sarah.chen@company.com",
    name: "Sarah Chen",
    role: "Lead",
    teamId: "team-alpha",
    jobTitle: "Engineering Lead",
    isActive: true,
    lastUpdateSubmitted: "2026-02-12",
    avatar: "",
  },
  {
    id: "u2",
    email: "alex.rivera@company.com",
    name: "Alex Rivera",
    role: "Member",
    teamId: "team-alpha",
    jobTitle: "Frontend Developer",
    isActive: true,
    lastUpdateSubmitted: "2026-02-12",
    avatar: "",
  },
  {
    id: "u3",
    email: "jordan.patel@company.com",
    name: "Jordan Patel",
    role: "Member",
    teamId: "team-alpha",
    jobTitle: "Backend Developer",
    isActive: true,
    lastUpdateSubmitted: "2026-02-11",
    avatar: "",
  },
  {
    id: "u4",
    email: "maya.williams@company.com",
    name: "Maya Williams",
    role: "Member",
    teamId: "team-alpha",
    jobTitle: "Full Stack Developer",
    isActive: true,
    lastUpdateSubmitted: null,
    avatar: "",
  },
];

export const mockUsers: User[] = baseUsers.map((user) => ({
  ...user,
  _id: user.id,
}));

const baseTasks: Omit<Task, "isSubtask" | "parentTaskId" | "parentTaskTitle">[] = [
  {
    id: "t1",
    title: "Design new onboarding flow",
    summary: "Create wireframes and high-fidelity mockups for user onboarding",
    description: "Design a comprehensive onboarding experience that guides new users through the platform's key features. Include tooltips, progress indicators, and a welcome tutorial.",
    assigneeId: "u2",
    status: "IN_PROGRESS",
    priority: "High",
    startDate: "2026-02-03",
    dueDate: "2026-02-14",
    reportedBy: "u1",
    createdAt: "2026-02-01",
    updates: [
      { date: "2026-02-03", note: "Started working on wireframes for the first three screens.", updatedBy: "u2" },
      { date: "2026-02-07", note: "Wireframes approved. Moving to high-fidelity mockups.", updatedBy: "u2", subtaskCompletions: ["st1-1", "st1-2"] },
      { date: "2026-02-12", note: "Mockups 80% complete, finishing up animations.", updatedBy: "u2", subtaskCompletions: ["st1-3"] },
    ],
    suggestedSubtasks: [
      { id: "st1-1", title: "Wireframe welcome screen", description: "Create low-fi wireframe for the welcome page", status: "DONE", suggestedDate: "2026-02-05" },
      { id: "st1-2", title: "Wireframe feature tour", description: "Design the interactive feature tour flow", status: "DONE", suggestedDate: "2026-02-07" },
      { id: "st1-3", title: "High-fidelity mockups", description: "Convert wireframes to high-fidelity designs", status: "DONE", suggestedDate: "2026-02-12" },
      { id: "st1-4", title: "Animation prototypes", description: "Create motion design prototypes", status: "TODO", suggestedDate: "2026-02-14" },
    ],
  },
  {
    id: "t2",
    title: "Implement authentication API",
    summary: "Build JWT-based auth endpoints with refresh token support",
    description: "Implement login, register, logout, and token refresh endpoints. Include rate limiting and account lockout after failed attempts.",
    assigneeId: "u3",
    status: "DONE",
    priority: "High",
    startDate: "2026-01-27",
    dueDate: "2026-02-07",
    reportedBy: "u1",
    createdAt: "2026-01-25",
    updates: [
      { date: "2026-01-28", note: "Set up JWT middleware and basic login endpoint.", updatedBy: "u3", subtaskCompletions: ["st2-1"] },
      { date: "2026-02-03", note: "All endpoints implemented. Writing integration tests.", updatedBy: "u3", subtaskCompletions: ["st2-2", "st2-3"] },
      { date: "2026-02-06", note: "All tests passing. Ready for review.", updatedBy: "u3" },
      { date: "2026-02-07", note: "Code reviewed and merged to main.", updatedBy: "u1" },
    ],
    suggestedSubtasks: [
      { id: "st2-1", title: "Login endpoint", description: "POST /auth/login", status: "DONE", suggestedDate: "2026-01-30" },
      { id: "st2-2", title: "Register endpoint", description: "POST /auth/register", status: "DONE", suggestedDate: "2026-02-01" },
      { id: "st2-3", title: "Token refresh", description: "POST /auth/refresh", status: "DONE", suggestedDate: "2026-02-04" },
    ],
  },
  {
    id: "t3",
    title: "Fix dashboard performance issues",
    summary: "Optimize slow-loading dashboard widgets and reduce bundle size",
    description: "The dashboard takes 4+ seconds to load on slower connections. Investigate lazy loading, code splitting, and query optimization.",
    assigneeId: "u2",
    status: "BLOCKED",
    priority: "High",
    startDate: "2026-02-10",
    dueDate: "2026-02-17",
    reportedBy: "u1",
    createdAt: "2026-02-09",
    updates: [
      { date: "2026-02-10", note: "Started profiling. Main bottleneck is the charts widget.", updatedBy: "u2" },
      { date: "2026-02-11", note: "Blocked waiting for the analytics team to provide a lighter data endpoint.", blockedReason: "Waiting for analytics team to expose a paginated API endpoint instead of returning all data at once.", updatedBy: "u2" },
    ],
    suggestedSubtasks: [],
  },
  {
    id: "t4",
    title: "Set up CI/CD pipeline",
    summary: "Configure GitHub Actions for automated testing and deployment",
    description: "Create workflows for running unit tests, linting, building, and deploying to staging/production environments.",
    assigneeId: "u3",
    status: "TODO",
    priority: "Medium",
    startDate: "2026-02-17",
    dueDate: "2026-02-21",
    reportedBy: "u1",
    createdAt: "2026-02-10",
    updates: [],
    suggestedSubtasks: [
      { id: "st4-1", title: "Set up test workflow", description: "Run unit tests on PR", status: "TODO", suggestedDate: "2026-02-18" },
      { id: "st4-2", title: "Set up deploy workflow", description: "Auto-deploy to staging on merge", status: "TODO", suggestedDate: "2026-02-20" },
    ],
  },
  {
    id: "t5",
    title: "Write API documentation",
    summary: "Document all REST API endpoints with examples using OpenAPI spec",
    description: "Create comprehensive API documentation covering all endpoints, request/response schemas, authentication, and error codes.",
    assigneeId: "u4",
    status: "IN_PROGRESS",
    priority: "Medium",
    startDate: "2026-02-10",
    dueDate: "2026-02-19",
    reportedBy: "u1",
    createdAt: "2026-02-08",
    updates: [
      { date: "2026-02-10", note: "Set up Swagger/OpenAPI config. Documenting auth endpoints first.", updatedBy: "u4" },
      { date: "2026-02-12", note: "Auth and user endpoints documented. Starting on task endpoints.", updatedBy: "u4" },
    ],
    suggestedSubtasks: [],
  },
  {
    id: "t6",
    title: "Add dark mode support",
    summary: "Implement theme switching with system preference detection",
    description: "Add dark mode to the entire application. Ensure all components, charts, and illustrations work in both themes.",
    assigneeId: "u4",
    status: "DONE",
    priority: "Low",
    startDate: "2026-02-03",
    dueDate: "2026-02-10",
    reportedBy: "u2",
    createdAt: "2026-02-01",
    updates: [
      { date: "2026-02-04", note: "Set up theme provider and CSS variables.", updatedBy: "u4" },
      { date: "2026-02-08", note: "All components themed. Testing edge cases.", updatedBy: "u4" },
      { date: "2026-02-10", note: "Dark mode complete and deployed.", updatedBy: "u4" },
    ],
    suggestedSubtasks: [],
  },
  {
    id: "t7",
    title: "Database migration to PostgreSQL",
    summary: "Migrate from SQLite to PostgreSQL for production readiness",
    description: "Plan and execute migration from SQLite to PostgreSQL, update all queries, test data integrity.",
    assigneeId: "u3",
    status: "TODO",
    priority: "High",
    startDate: "2026-02-24",
    dueDate: "2026-03-07",
    reportedBy: "u1",
    createdAt: "2026-02-12",
    updates: [],
    suggestedSubtasks: [],
  },
  {
    id: "t8",
    title: "Create user settings page",
    summary: "Build a settings page for profile, notifications, and preferences",
    description: "Allow users to update their profile picture, notification preferences, and display settings.",
    assigneeId: "u2",
    status: "TODO",
    priority: "Low",
    startDate: "2026-02-24",
    dueDate: "2026-02-28",
    reportedBy: "u1",
    createdAt: "2026-02-12",
    updates: [],
    suggestedSubtasks: [],
  },
  {
    id: "t9",
    title: "Implement email notification service",
    summary: "Set up transactional email for task assignments and updates",
    description: "Integrate with an email service to send notifications when tasks are assigned, updated, or approaching deadlines.",
    assigneeId: "u3",
    status: "IN_PROGRESS",
    priority: "Medium",
    startDate: "2026-02-10",
    dueDate: "2026-02-20",
    reportedBy: "u1",
    createdAt: "2026-02-09",
    updates: [
      { date: "2026-02-10", note: "Researching email providers. Leaning toward Resend.", updatedBy: "u3" },
    ],
    suggestedSubtasks: [],
  },
  {
    id: "t10",
    title: "Add keyboard shortcuts",
    summary: "Implement keyboard navigation and shortcuts for power users",
    description: "Add keyboard shortcuts for common actions: create task (Ctrl+N), search (Ctrl+K), navigate between views.",
    assigneeId: "u4",
    status: "TODO",
    priority: "Low",
    startDate: "2026-03-03",
    dueDate: "2026-03-10",
    reportedBy: "u2",
    createdAt: "2026-02-13",
    updates: [],
    suggestedSubtasks: [],
  },
];

export const mockTasks: Task[] = baseTasks.map((task) => ({
  ...task,
  isSubtask: false,
  parentTaskId: undefined,
  parentTaskTitle: undefined,
}));
